import js from "@eslint/js";
import sonarjs from "eslint-plugin-sonarjs";
import reactPlugin from "eslint-plugin-react";
import reactHooksPlugin from "eslint-plugin-react-hooks";

export default [
    js.configs.recommended,
    sonarjs.configs.recommended,
    {
        files: ["src/**/*.{js,jsx}"],
        plugins: {
            react: reactPlugin,
            "react-hooks": reactHooksPlugin,
        },
        languageOptions: {
            ecmaVersion: "latest",
            sourceType: "module",
            parserOptions: {
                ecmaFeatures: {
                    jsx: true,
                },
            },
            globals: {
                window: "readonly",
                document: "readonly",
                localStorage: "readonly",
                sessionStorage: "readonly",
                console: "readonly",
                setTimeout: "readonly",
                clearTimeout: "readonly",
                setInterval: "readonly",
                clearInterval: "readonly",
                fetch: "readonly",
                AbortSignal: "readonly",
                navigator: "readonly",
                location: "readonly",
                history: "readonly",
                URL: "readonly",
                URLSearchParams: "readonly",
                CustomEvent: "readonly",
                Event: "readonly",
                Image: "readonly",
                Date: "readonly",
                Array: "readonly",
                Object: "readonly",
                Number: "readonly",
                String: "readonly",
                Boolean: "readonly",
                Math: "readonly",
                JSON: "readonly",
                Map: "readonly",
                Set: "readonly",
                Promise: "readonly",
                encodeURIComponent: "readonly",
                decodeURIComponent: "readonly",
                isNaN: "readonly",
                parseInt: "readonly",
                parseFloat: "readonly",
                requestAnimationFrame: "readonly",
                cancelAnimationFrame: "readonly",
                atob: "readonly",
                btoa: "readonly",
                TextDecoder: "readonly",
                TextEncoder: "readonly",
                Response: "readonly",
                Request: "readonly",
                Headers: "readonly",
                XMLHttpRequest: "readonly",
                MediaMetadata: "readonly",
                Blob: "readonly",
                FileReader: "readonly",
                crypto: "readonly",
            },
        },
        rules: {
            "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
            "no-empty": ["warn", { allowEmptyCatch: true }],
            "no-console": "off",
            "react/prop-types": "off",
            "react/react-in-jsx-scope": "off",
            "sonarjs/no-duplicate-string": "off",
            "sonarjs/cognitive-complexity": "off",
            "sonarjs/no-nested-template-literals": "off",
            "sonarjs/no-redundant-jump": "warn",
            "sonarjs/prefer-immediate-return": "warn",
            "sonarjs/no-small-switch": "off",
            "sonarjs/no-ignored-exceptions": "off",
            "sonarjs/super-linear-regex": "off",
            "sonarjs/regex-complexity": "off",
            "sonarjs/no-hardcoded-ip": "off",
            "sonarjs/pseudo-random": "off",
            "sonarjs/different-types-comparison": "off",
            "sonarjs/no-misleading-array-reverse": "off",
            "sonarjs/no-nested-conditional": "off",
        },
    },
    {
        ignores: [
            "dist/**",
            "node_modules/**",
            "build/**",
            "*.json",
            "homepageLists.json",
            "src/pages/Vods.jsx",
            "src/pages/VodPlay.jsx",
        ],
    },
];
