export const SOURCES = {
    SOURCE_C: "source_c",
    SOURCE_K: "source_k",
    SOURCE_O: "source_o",
    SOURCE_R: "source_r",
};

export const TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p";
export const TMDB_IMAGE_SIZES = {
    POSTER: "w500",
    BACKDROP: "original", // Tối ưu cho màn hình 1920px
    THUMBNAIL: "w780",
    SMALL: "w342",
    TINY: "w92",
    LOGO: "h60",
};

export const CATEGORIES = [
    {
        id: "history",
        title: "Lịch Sử",
        titleKey: "vods.history",
        type: "lich-su",
        source: "",
        isView: false,
    },
    {
        id: "favorites",
        title: "Yêu Thích",
        titleKey: "vods.favorites",
        type: "yeu-thich",
        source: "",
        isView: false,
    },
    {
        id: "new",
        title: "Phim Mới Cập Nhật",
        titleKey: "vods.newMovies",
        type: "danh-sach/phim-moi-cap-nhat",
        source: "source_k",
        isView: true,
        useV1: false,
    },
    {
        id: "phim-le",
        title: "Phim Lẻ Mới",
        titleKey: "vods.newSingleMovies",
        type: "danh-sach/phim-le",
        source: "source_k",
        useV1: true,
    },
    {
        id: "phim-bo",
        title: "Phim Bộ Mới",
        titleKey: "vods.newSeriesMovies",
        type: "danh-sach/phim-bo",
        source: "source_k",
        useV1: true,
    },
    {
        id: "phim-chieu-rap",
        title: "Phim Chiếu Rạp",
        titleKey: "vods.cinemaMovies",
        type: "danh-sach/phim-chieu-rap",
        source: "source_k",
        useV1: true,
    },
    {
        id: "tv-shows",
        title: "TV Shows",
        titleKey: "vods.tvShows",
        type: "danh-sach/tv-shows",
        source: "source_k",
        useV1: true,
    },
    {
        id: "hoat-hinh",
        title: "Hoạt Hình",
        titleKey: "vods.animation",
        type: "danh-sach/hoat-hinh",
        source: "source_k",
        useV1: true,
    },
    {
        id: "trung-quoc",
        title: "Phim Trung Quốc",
        titleKey: "vods.china",
        type: "quoc-gia/trung-quoc",
        source: "source_o",
        useV1: true,
    },
    {
        id: "han-quoc",
        title: "Phim Hàn Quốc",
        titleKey: "vods.korea",
        type: "quoc-gia/han-quoc",
        source: "source_o",
        useV1: true,
    },
    {
        id: "viet-nam",
        title: "Phim Việt Nam",
        titleKey: "vods.vietnam",
        type: "quoc-gia/viet-nam",
        source: "source_o",
        useV1: true,
    },
    {
        id: "action",
        title: "Phim Hành Động",
        titleKey: "vods.action",
        type: "the-loai/hanh-dong",
        source: "source_o",
        useV1: true,
    },
    {
        id: "horror",
        title: "Kinh Dị",
        titleKey: "vods.horror",
        type: "the-loai/kinh-di",
        source: "source_o",
        useV1: true,
    },
    {
        id: "romance",
        title: "Phim Tình Cảm",
        titleKey: "vods.romance",
        type: "the-loai/tinh-cam",
        source: "source_o",
        useV1: true,
    },
    {
        id: "phim-thuyet-minh",
        title: "Phim Thuyết Minh",
        titleKey: "vods.voiceoverMovies",
        type: "danh-sach/phim-thuyet-minh",
        source: "source_k",
        useV1: true,
    },
    {
        id: "phim-long-tieng",
        title: "Phim Lồng Tiếng",
        titleKey: "vods.dubbedMovies",
        type: "danh-sach/phim-long-tieng",
        source: "source_k",
        useV1: true,
    },
];
