export const SOURCES = {
    SOURCE_C: "source_c",
    SOURCE_K: "source_k",
    SOURCE_O: "source_o",
    SOURCE_R: "source_r",
};

export const FILTER_YEARS = Array.from({ length: 26 }, (_, i) =>
    (2025 - i).toString(),
);

export const FILTER_SOURCES = [
    { id: "all", name: "Tất cả" },
    { id: SOURCES.SOURCE_O, name: "Từ O" },
    { id: SOURCES.SOURCE_K, name: "Từ K" },
    { id: SOURCES.SOURCE_C, name: "Từ C" },
];

export const FILTER_TYPE_LIST = [
    { slug: "phim-bo-dang-chieu", name: "Đang Chiếu" },
    { slug: "phim-bo-hoan-thanh", name: "Hoàn Thành" },
    { slug: "hoat-hinh", name: "Hoạt Hình" },
    { slug: "phim-long-tieng", name: "Lồng Tiếng" },
    { slug: "phim-bo", name: "Phim Bộ" },
    { slug: "phim-le", name: "Phim Lẻ" },
    { slug: "phim-sap-chieu", name: "Sắp Chiếu" },
    { slug: "phim-thuyet-minh", name: "Thuyết Minh" },
    { slug: "tv-shows", name: "TV Shows" },
    { slug: "phim-vietsub", name: "Vietsub" },
];

export const TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p";
export const TMDB_IMAGE_SIZES = {
    POSTER: "w500",
    BACKDROP: "original", // Tối ưu cho màn hình 1920px
    THUMBNAIL: "w780",
    SMALL: "w342",
    TINY: "w92",
    LOGO: "h60",
};

export const CATEGORIES = [
    {
        id: "history",
        title: "Lịch Sử",
        titleKey: "vods.history",
        type: "lich-su",
        source: "",
        isView: false,
    },
    {
        id: "favorites",
        title: "Yêu Thích",
        titleKey: "vods.favorites",
        type: "yeu-thich",
        source: "",
        isView: false,
    },
    {
        id: "new",
        title: "Phim Mới Cập Nhật",
        titleKey: "vods.newMovies",
        type: "danh-sach/phim-moi-cap-nhat",
        source: "source_k",
        isView: true,
        useV1: false,
    },
    {
        id: "phim-le",
        title: "Phim Lẻ Mới",
        titleKey: "vods.newSingleMovies",
        type: "danh-sach/phim-le",
        source: "source_k",
        useV1: true,
    },
    {
        id: "phim-bo",
        title: "Phim Bộ Mới",
        titleKey: "vods.newSeriesMovies",
        type: "danh-sach/phim-bo",
        source: "source_k",
        useV1: true,
    },
    {
        id: "phim-chieu-rap",
        title: "Phim Chiếu Rạp",
        titleKey: "vods.cinemaMovies",
        type: "danh-sach/phim-chieu-rap",
        source: "source_k",
        useV1: true,
    },
    {
        id: "tv-shows",
        title: "TV Shows",
        titleKey: "vods.tvShows",
        type: "danh-sach/tv-shows",
        source: "source_k",
        useV1: true,
    },
    {
        id: "hoat-hinh",
        title: "Hoạt Hình",
        titleKey: "vods.animation",
        type: "danh-sach/hoat-hinh",
        source: "source_k",
        useV1: true,
    },
    {
        id: "trung-quoc",
        title: "Phim Trung Quốc",
        titleKey: "vods.china",
        type: "quoc-gia/trung-quoc",
        source: "source_o",
        useV1: true,
    },
    {
        id: "han-quoc",
        title: "Phim Hàn Quốc",
        titleKey: "vods.korea",
        type: "quoc-gia/han-quoc",
        source: "source_o",
        useV1: true,
    },
    {
        id: "viet-nam",
        title: "Phim Việt Nam",
        titleKey: "vods.vietnam",
        type: "quoc-gia/viet-nam",
        source: "source_o",
        useV1: true,
    },
    {
        id: "action",
        title: "Phim Hành Động",
        titleKey: "vods.action",
        type: "the-loai/hanh-dong",
        source: "source_o",
        useV1: true,
    },
    {
        id: "horror",
        title: "Kinh Dị",
        titleKey: "vods.horror",
        type: "the-loai/kinh-di",
        source: "source_o",
        useV1: true,
    },
    {
        id: "romance",
        title: "Phim Tình Cảm",
        titleKey: "vods.romance",
        type: "the-loai/tinh-cam",
        source: "source_o",
        useV1: true,
    },
    {
        id: "phim-thuyet-minh",
        title: "Phim Thuyết Minh",
        titleKey: "vods.voiceoverMovies",
        type: "danh-sach/phim-thuyet-minh",
        source: "source_k",
        useV1: true,
    },
    {
        id: "phim-long-tieng",
        title: "Phim Lồng Tiếng",
        titleKey: "vods.dubbedMovies",
        type: "danh-sach/phim-long-tieng",
        source: "source_k",
        useV1: true,
    },
];

export const SOURCE_C_COUNTRIES = [
    { slug: "au-my", name: "Âu Mỹ", id: "48" },
    { slug: "anh", name: "Anh", id: "49" },
    { slug: "trung-quoc", name: "Trung Quốc", id: "50" },
    { slug: "indonesia", name: "Indonesia", id: "51" },
    { slug: "viet-nam", name: "Việt Nam", id: "52" },
    { slug: "argentina", name: "Argentina", id: "53" },
    { slug: "ao", name: "Áo", id: "54" },
    { slug: "uc", name: "Úc", id: "55" },
    { slug: "bangladesh", name: "Bangladesh", id: "56" },
    { slug: "brazil", name: "Brazil", id: "57" },
    { slug: "bahamas", name: "Bahamas", id: "58" },
    { slug: "belarus", name: "Belarus", id: "59" },
    { slug: "canada", name: "Canada", id: "60" },
    { slug: "thuy-si", name: "Thụy Sĩ", id: "61" },
    { slug: "bo-bien-nga", name: "Bờ Biển Ngà", id: "62" },
    { slug: "chile", name: "Chile", id: "63" },
    { slug: "colombia", name: "Colombia", id: "64" },
    { slug: "costa-rica", name: "Costa Rica", id: "65" },
    { slug: "duc", name: "Đức", id: "66" },
    { slug: "dan-mach", name: "Đan Mạch", id: "67" },
    { slug: "tay-ban-nha", name: "Tây Ban Nha", id: "68" },
    { slug: "phap", name: "Pháp", id: "69" },
    { slug: "greenland", name: "Greenland", id: "70" },
    { slug: "hong-kong", name: "Hồng Kông", id: "71" },
    { slug: "han-quoc", name: "Hàn Quốc", id: "72" },
    { slug: "nhat-ban", name: "Nhật Bản", id: "73" },
    { slug: "thai-lan", name: "Thái Lan", id: "74" },
    { slug: "dai-loan", name: "Đài Loan", id: "75" },
    { slug: "nga", name: "Nga", id: "76" },
    { slug: "ha-lan", name: "Hà Lan", id: "77" },
    { slug: "quoc-gia-khac", name: "Quốc gia khác", id: "78" },
    { slug: "philippines", name: "Philippines", id: "95" },
    { slug: "an-do", name: "Ấn Độ", id: "96" },
];

export const SOURCE_C_CATEGORIES = [
    { slug: "hanh-dong", name: "Hành Động", id: "7" },
    { slug: "phieu-luu", name: "Phiêu Lưu", id: "8" },
    { slug: "hoat-hinh", name: "Hoạt Hình", id: "9" },
    { slug: "phim-hai", name: "Phim Hài", id: "10" },
    { slug: "hinh-su", name: "Hình Sự", id: "11" },
    { slug: "tai-lieu", name: "Tài Liệu", id: "12" },
    { slug: "chinh-kich", name: "Chính Kịch", id: "13" },
    { slug: "gia-dinh", name: "Gia Đình", id: "14" },
    { slug: "gia-tuong", name: "Giả Tưởng", id: "15" },
    { slug: "lich-su", name: "Lịch Sử", id: "16" },
    { slug: "kinh-di", name: "Kinh Dị", id: "17" },
    { slug: "phim-nhac", name: "Phim Nhạc", id: "18" },
    { slug: "bi-an", name: "Bí Ẩn", id: "19" },
    { slug: "lang-man", name: "Lãng Mạn", id: "20" },
    { slug: "khoa-hoc-vien-tuong", name: "Khoa Học Viễn Tưởng", id: "21" },
    { slug: "gay-can", name: "Gây Cấn", id: "22" },
    { slug: "chien-tranh", name: "Chiến Tranh", id: "23" },
    { slug: "mien-tay", name: "Miền Tây", id: "24" },
    { slug: "co-trang", name: "Cổ Trang", id: "142" },
    { slug: "tam-ly", name: "Tâm Lý", id: "143" },
    { slug: "phim-18", name: "Phim 18+", id: "144" },
    { slug: "tinh-cam", name: "Tình Cảm", id: "155" },
];
